# Sets Travis to run the Ruby specs on OS X machines which are required to
# build the native extensions of Xcodeproj.
#
language: objective-c

env:
  - RVM_RUBY_VERSION=system
  - RVM_RUBY_VERSION=ruby-2.0.0-p247

addons:
 code_climate:
   repo_token: 6806682857c395155713502a40d890d1d694191bb29e53ac37d435d4fea760eb

before_install:
  - export LANG=en_US.UTF-8
  - curl http://curl.haxx.se/ca/cacert.pem -o /usr/local/share/cacert.pem
  - source ~/.rvm/scripts/rvm
  - if [[ $RVM_RUBY_VERSION != 'system' ]]; then rvm install $RVM_RUBY_VERSION; fi
  - rvm use $RVM_RUBY_VERSION
  - if [[ $RVM_RUBY_VERSION == 'system' ]]; then export ARCHFLAGS=-Wno-error=unused-command-line-argument-hard-error-in-future; fi
  - if [[ $RVM_RUBY_VERSION == 'system' ]]; then sudo gem install bundler --no-ri --no-rdoc; else gem install bundler --no-ri --no-rdoc; fi

install:
  - bundle install --without=debugging documentation --path ./travis_bundle_dir

script: bundle exec rake spec
